# Generated by Django 4.1.1 on 2022-10-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trend_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Consumer Product', 'Consumer Product'), ('Industrial Product', 'Industrial Product'), ('Service Product', 'Service Product')], max_length=200, null=True),
        ),
    ]
